### ISSUE TITLE
Tracking Issue: Tutorial Improvements I

### ISSUE THREAD

**Issue by KyleMayes** [KyleMayes/vulkanalia#151]
- [x] Rework how compatibility extensions (needed for macOS) are integrated into the tutorial
- [x] Update fixed functions chapter to make placement of pipeline layout initialization more clear
- [x] Investigate whether simultaneous use command buffer flag should be included in command buffers chapter
- [x] Remove reference to unused sparse buffer memory flag in vertex buffer creation chapter
- [x] Fix descriptor set layout initialization in descriptor pool chapter
- [x] Fix reference to sample count flags in texture images chapter
- [x] Fix resizing logic in swapchain recreation chapter
- [x] Fix `copy_bufer_to_image` typo in texture images chapter
- [x] `glm` to `cgmath`
- [x] Specify swapchain images views and depth/stencil images should have mipmap = 1
- [x] Fix `pick_physical_device` w.r.t. clarity of `msaa_samples` addition
- [x] Chapter 37 typo
- [x] Chapter 37 memory leak
- [x] specify assets are different from original C++ tutorial #147
- [x] Look into Wayland issues with device selection https://github.com/KyleMayes/vulkanalia/issues/151#issuecomment-1669458103
- [x] Improve aligned memory allocation approach #182

**Comment by chuigda** [comment]
Let me help with the glm -> cgmath update

**Comment by dsvensson** [comment]
Issues with tutorials on Ubuntu with Wayland and NVIDIA GPU:

Following needed to pass initialization:
```diff
-        .message_type(vk::DebugUtilsMessageTypeFlagsEXT::all())
+        .message_type(vk::DebugUtilsMessageTypeFlagsEXT::VALIDATION | vk::DebugUtilsMessageTypeFlagsEXT::GENERAL | vk::DebugUtilsMessageTypeFlagsEXT::PERFORMANCE)
```

Even so the examples select llvmpipe rather than NVIDIA GPU because the `instance.get_physical_device_surface_support_khr` fails with the given surface. Think I've seen something similar elsewhere. Maybe the window has to be presented before, or it's something with the surface format.

**Comment by gudzpoz** [comment]
Regarding `DEVICE_ADDRESS_BINDING`, on devices supporting `DEVICE_ADDRESS_BINDING`, the current tutorial code seem to crash when `debug_callback` receives a `vk::DebugUtilsMessageTypeFlagsEXT::DEVICE_ADDRESS_BINDING` message, when `data.message` is a null pointer:

> `pMessage` is `NULL` if `messageTypes` is equal to `VK_DEBUG_UTILS_MESSAGE_TYPE_DEVICE_ADDRESS_BINDING_BIT_EXT`, or a null-terminated UTF-8 string detailing the trigger conditions.
>
> https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDebugUtilsMessengerCallbackDataEXT.html

(OS: Arch Linux, Vulkan: `Vulkan Instance Version: 1.3.279`, Driver: `vulkan-radeon 1:24.1.4-2`)

I work around it like this:

```diff
-    let message = unsafe { CStr::from_ptr(data.message) }.to_string_lossy();
+    let message = if !data.message.is_null() {
+        unsafe { CStr::from_ptr(data.message) }.to_string_lossy()
+    } else {
+        assert!(message_type == vk::DebugUtilsMessageTypeFlagsEXT::DEVICE_ADDRESS_BINDING);
+        let binding = unsafe { &*(data.next as *const vk::DeviceAddressBindingCallbackDataEXT) };
+        Cow::Owned(format!(
+            "{:?}: {} bytes @ 0x{:x} {:?}",
+            binding.binding_type, binding.size, binding.base_address, binding.flags
+        ))
+    };
```

**Comment by KyleMayes** [comment]
I think the primary fix is to just avoid using `DEVICE_ADDRESS_BINDING` as mentioned in https://github.com/KyleMayes/vulkanalia/issues/270#issuecomment-2209914941 and in the previous comment.

I have a note in the tutorial that using `vk::DebugUtilsMessageTypeFlagsEXT::all()` could lead to validation errors, but it seems I should just update the tutorial to avoid `::all()` here (though keep the note calling this out `::all()` as a danger since it can cause errors if it enables flags you aren't expecting).

**Comment by KyleMayes** [comment]
All the tracked issues are fixed or I couldn't replicate them (e.g., the Wayland issue).
